name: Check PR branch

on: 
  pull_request:
    types:
      - opened
    branches-ignore:
      - new-pr

permissions:
  pull-requests: write

jobs:
  check_pr_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            It looks like you made your PR not against the `new-pr` branch. If you want to submit a App, you must target the `new-pr` branch.
