name: "Pull Request Labeler"
on:
- issue_comment

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v5.0.0-beta
      with:
       configuration-path: .github/labeler.yaml
